name = "Yofo"
author = "xgroleau"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1e3e8d248e743c82837ff9597d2c7120ac4f86513760ca8bc1088a33e79541e"

[versions]
fabric = "0.16.5"
minecraft = "1.20.2"
