name = "Yofo"
author = "xgroleau"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9c2245f8f88fbf866703fdb82712af582e8830c8649c2e25ef1b0cdd9aeaf1f"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
